### PR TITLE
Human Liver Microsomal Stability Code

### PR DESCRIPTION
**Pull request by masroor07**
#### The pull request contains the code for HLM model
- [X] Modified code Base
- [X] Added checkpoints
- [X] Edited metadata.json

### CODE REVIEW

**Comment by GemmaTuron** [comment]
@masroor07 
I've solved the git-lfs issue
please modify the model slug to ncats-hlm and make the pr again

**Comment by masroor07** [comment]
> @masroor07
> I've solved the git-lfs issue
> please modify the model slug to ncats-hlm and make the pr again

alright! will do it right away!

**Comment by masroor07** [comment]
The model seems to be again failing at setting up the environment, i am not facing this issue locally!

**Comment by GemmaTuron** [comment]
Hi @masroor07 

Have you tried to install the model in you system through Ersilia, this should reproduce the error
`ersilia -v fetch eos31ve --repo_path <path-to-your-repo>`

**Comment by masroor07** [comment]
> Hi @masroor07
> 
> Have you tried to install the model in you system through Ersilia, this should reproduce the error `ersilia -v fetch eos31ve --repo_path <path-to-your-repo>`

alright, i will try to run it through ersilia!

**Comment by GemmaTuron** [comment]
As detailed in the example of a model incorporation, this step is necessary before doing a PR otherwise you cannot check whether the model is properly integrated within ersilia.
See: https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/example-of-the-model-incorporation-workflow

**Comment by GemmaTuron** [comment]
I'll close this PR and merge the PR from my fork since I cannot push the changes I made to the dockerfile and some other additions via @masroor07 's github

**Pull request closed without merging**
